language: r
cache: packages

env:
  - SURVEYSD_ADDITIONAL_TEST = FALSE

apt_packages:
  - ghostscript

matrix:
  include:
    - r: devel
    - r: release
      r_packages:
      - covr
      - lintr
      - pkgdown
      after_success:
      - R CMD INSTALL $PKG_TARBALL
      - Rscript -e 'covr::coveralls()'
      - Rscript -e 'lintr::lint_package()'
      deploy:
        provider: script
        script: Rscript -e 'pkgdown::deploy_site_github()'
        skip_cleanup: true

notifications:
  email:
    on_success: change
    on_failure: change
