language: r
cache: packages

matrix:
  include:
    - r: devel
    - r: release
      r_github_packages:
      - r-lib/covr
      - jimhester/lintr
      after_success:
      - R CMD INSTALL $PKG_TARBALL
      - Rscript -e 'covr::coveralls()'
      - Rscript -e 'lintr::lint_package()'

notifications:
  email:
    on_success: change
    on_failure: change
