language: r
r:
  - release
  - devel
cache: packages

after_success:
  - Rscript -e 'install.packages("covr");library(covr);coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
