# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rollMeanC <- function(x, k, type) {
    .Call('_surveysd_rollMeanC', PACKAGE = 'surveysd', x, k, type)
}

rollSumC <- function(x, k, type) {
    .Call('_surveysd_rollSumC', PACKAGE = 'surveysd', x, k, type)
}

weightedRatioC <- function(x, w) {
    .Call('_surveysd_weightedRatioC', PACKAGE = 'surveysd', x, w)
}

weightedSumC <- function(x, w) {
    .Call('_surveysd_weightedSumC', PACKAGE = 'surveysd', x, w)
}

